// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/7/2024, 5:42:36 PM
const configMerger = require("/home/project/test/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/project/test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/plugins/**/*.{js,ts,mjs}","/home/project/test/composables/**/*.{js,ts,mjs}","/home/project/test/utils/**/*.{js,ts,mjs}","/home/project/test/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/test/app.config.{js,ts,mjs}"] } }));

module.exports = config
